주어진 데이터 셋에서 age컬럼 상위 20개의 데이터를 구한 다음 <br>
f1의 결측치를 중앙값으로 채운다. <br>
그리고 f4가 ISFJ와 f5가 20 이상인 <br>
f1의 평균값을 출력하시오!

- 데이터셋 : basic1.csv
- 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작
- File -> Editor Type -> Script

In [1]:
import pandas as pd

df = pd.read_csv("basic1.csv")

df.head()

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [3]:
 age_top20 = df.sort_values('age', ascending=False).head(20)
 age_top20

      id    age city    f1  f2   f3    f4         f5
96  id97  100.0   경기   NaN   0  NaN  INFP  67.886373
36  id37  100.0   부산   NaN   0  NaN  ESTP  33.308999
44  id45   97.0   대구  88.0   0  NaN  ENFJ  13.049921
51  id52   97.0   대구  82.0   1  NaN  ISFJ  90.496999
91  id92   97.0   경기  78.0   1  NaN  INFP  97.381034
9   id10   95.0   서울  74.0   1  NaN  ISFP  98.429899
45  id46   93.0   대구   NaN   0  NaN  ESTJ  67.886373
77  id78   92.0   경기  96.0   1  NaN  INTJ  69.730313
95  id96   92.0   경기  53.0   1  NaN  ENTJ  52.667078
72  id73   90.0   경기   NaN   1  NaN  ISFJ  73.586397
20  id21   90.0   부산   NaN   1  NaN  ISFP  29.269869
87  id88   89.0   경기  75.0   0  NaN  ESTJ  60.339826
62  id63   88.0   경기  86.0   1  NaN  ISFJ  73.586397
65  id66   87.0   경기   NaN   1  NaN  ISFP  17.252986
37  id38   87.0   부산   NaN   1  NaN  ESTP  83.685380
60  id61   87.0   경기  62.0   2  NaN  INTP  69.730313
49  id50   86.0   대구  78.0   1  NaN  ENFP  60.339826
80  id81   86.0   경기  50.0   1  NaN  ISFJ  37.113739
30  id31   86.0   부산  77.0   0  NaN  ESFJ  73.586397
93  id94   84.0   경기   NaN   1  NaN  ESTJ  90.496999

In [4]:
age_top20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 96 to 93
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20 non-null     object
 1   age     20 non-null     float64
 2   city    20 non-null     object
 3   f1      12 non-null     float64
 4   f2      20 non-null     int64
 5   f3      0 non-null      object
 6   f4      20 non-null     object
 7   f5      20 non-null     float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.9+ KB

In [5]:
med = age_top20['f1'].median()
med

77.5

In [6]:
age_top20['f1'].fillna(med, inplace=True)
age_top20

      id    age city    f1  f2   f3    f4         f5
96  id97  100.0   경기  77.5   0  NaN  INFP  67.886373
36  id37  100.0   부산  77.5   0  NaN  ESTP  33.308999
44  id45   97.0   대구  88.0   0  NaN  ENFJ  13.049921
51  id52   97.0   대구  82.0   1  NaN  ISFJ  90.496999
91  id92   97.0   경기  78.0   1  NaN  INFP  97.381034
9   id10   95.0   서울  74.0   1  NaN  ISFP  98.429899
45  id46   93.0   대구  77.5   0  NaN  ESTJ  67.886373
77  id78   92.0   경기  96.0   1  NaN  INTJ  69.730313
95  id96   92.0   경기  53.0   1  NaN  ENTJ  52.667078
72  id73   90.0   경기  77.5   1  NaN  ISFJ  73.586397
20  id21   90.0   부산  77.5   1  NaN  ISFP  29.269869
87  id88   89.0   경기  75.0   0  NaN  ESTJ  60.339826
62  id63   88.0   경기  86.0   1  NaN  ISFJ  73.586397
65  id66   87.0   경기  77.5   1  NaN  ISFP  17.252986
37  id38   87.0   부산  77.5   1  NaN  ESTP  83.685380
60  id61   87.0   경기  62.0   2  NaN  INTP  69.730313
49  id50   86.0   대구  78.0   1  NaN  ENFP  60.339826
80  id81   86.0   경기  50.0   1  NaN  ISFJ  37.113739
30  id31   86.0   부산  77.0   0  NaN  ESFJ  73.586397
93  id94   84.0   경기  77.5   1  NaN  ESTJ  90.496999

In [7]:
# f4가 ISFJ와 f5가 20 이상인 f1의 평균
mean_f1 = age_top20[(age_top20['f4'] == 'ISFJ') & (age_top20['f5'] >= 20)]['f1'].mean()
mean_f1

73.875