## 결측치 제거 및 그룹 합계에서 조건에 맞는 값 찾아 출력
- 주어진 데이터 중 basic1.csv에서 'f1'컬럼 결측 데이터를 제거하고, 'city'와 'f2'을 기준으로 묶어 합계를 구하고, 'city가 경기이면서 f2가 0'인 조건에 만족하는 f1 값을 구하시오
- 데이터셋 : basic1.csv
- 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작

In [1]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
import numpy as np

In [2]:
# f1컬럼 결측치 제거
df = pd.read_csv('basic1.csv')
df.head()

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [15]:
drop_df = df.dropna(subset=['f1'])
drop_df.isna().sum()

id       0
age      0
city     0
f1       0
f2       0
f3      65
f4       0
f5       0
dtype: int64

In [26]:
# 그룹 합계 계산
df2 = df.groupby(['city', 'f2']).sum()
df2.head()

                                                        id     age     f1  \
city f2
경기   0   id60id62id65id69id72id74id75id76id77id79id80id...  1088.9  833.0
     1   id63id66id67id70id73id78id81id83id87id89id92id...   976.0  670.0
     2                                id61id64id68id71id98   239.0  311.0
대구   0        id40id41id43id44id45id46id48id49id51id53id57   578.0  527.0
     1                            id47id50id52id54id56id59   393.6  235.0

          f3                                                 f4           f5
city f2
경기   0   vip  ESFPINTPISFPESTJESTJESTPESTPENTJINFPINTJISFPEN...  1391.927648
     1   vip  ISFJISFPISFJISTPISFJINTJISFJENTPISFPENTJINFPES...   935.958628
     2     0                               INTPESFPISFPISFPINFP   362.300060
대구   0     0       ENFPENFJISTPINTPENFJESTJENFPINTPISTJESTPISFJ   371.184620
     1   vip                           ESTJENFPISFJENFJESTJESFJ   404.779978

In [31]:
# 조건에 맞는 값 출력
# 'city가 경기이면서 f2가 0'인 조건에 만족하는 f1
print(df2.iloc[0]['f1'])

833.0

## Hint
- 그룹 합계

In [ ]:
import pandas as pd
df = pd.DataFrame({'User': ['네모', '네모',
                              '세모', '세모'],
                   'Max Speed': [120., 240., 57., 41.]})
df

In [ ]:
df.groupby(['User']).mean()

## 풀이

In [ ]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.read_csv('../input/bigdatacertificationkr/basic1.csv')
df.head()

In [ ]:
# f1컬럼 결측치 제거
df = df[~df['f1'].isnull()]

In [ ]:
# 그룹 합계 계산
df2 = df.groupby(['city','f2']).sum()
df2

In [ ]:
# 조건에 맞는 값 출력
print(df2.iloc[0]['f1'])